[project]
name = "animegan2"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "lightning>=2.5.2",
    "mlflow>=3.1.1",
    "opencv-python>=4.11.0.86",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "wandb>=0.20.1",
]
